apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - env: stage
            prefix: "stage-"
          - env: prod
            prefix: ""
  template:
    metadata:
      name: "{{.prefix}}nginx"
    spec:
      project: default
      source:
        repoURL: https://github.com/lapeko/k12t_lab.git
        targetRevision: HEAD
        path: apps/nginx/k8s/overlays/{{.env}}
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.prefix}}nginx"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
